version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backendnet

  migrate:
    image: migrate/migrate
    container_name: db_migrate
    depends_on:
      - db
    volumes:
      - ./db/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@db:5432/mydb?sslmode=disable",
      "up"
    ]
    networks:
      - backendnet
    restart: on-failure

  app:
    build: .
    container_name: my_go_app
    ports:
      - "8082:8080"
    depends_on:
      - db
      - migrate
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_SSL_MODE: disable
      API_PORT: 8080
    networks:
      - backendnet

volumes:
  pgdata:

networks:
  backendnet:
